micronaut:
  application:
    name: bookmanager
  server:
    cors:
      enabled: true
# https://micronaut-projects.github.io/micronaut-sql/latest/guide/configurationreference.html#io.micronaut.configuration.jdbc.dbcp.DatasourceConfiguration
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
#    schema-generate: CREATE_DROP flywayを使うなら不要
    dialect: H2
jpa:
  default:
    packages-to-scan:
      - 'bookmanager.infra.dtos'
    entity-scan:
      packages:
        - 'bookmanager.infra.dtos'
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        # 以下を設定しないと、DTOでSQLを作成したときにアンダースコア区切りにならない
        # https://github.com/micronaut-projects/micronaut-data/issues/520
        physical_naming_strategy: "io.micronaut.data.hibernate.naming.DefaultPhysicalNamingStrategy"
        show_sql: true
flyway:
  datasources:
    default:
      enabled: true