micronaut:
  application:
    name: bookmanager
datasources:
  default:
    url: jdbc:h2:mem:devDb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
    schema-generate: CREATE_DROP
    dialect: H2
jpa:
  default:
    entity-scan:
      packages: 'bookmanager.infra.models'
    properties:
      hibernate:
        hbm2ddl:
          auto: update
        show_sql: true